from roadmapper.roadmap import Roadmap
from roadmapper.timelinemode import TimelineMode

roadmap = Roadmap(2560,1440, colour_theme="BLUEMOUNTAIN")
roadmap.set_title("Software Engineering Interview Preparation Roadmap")
roadmap.set_subtitle("the hard way")
roadmap.set_timeline(TimelineMode.WEEKLY, start="2023-01-01", number_of_items=49)

group = roadmap.add_group("Core Product Work Stream")

task = group.add_task("Base Functionality", "2023-01-01", "2023-10-31")
task.add_milestone("v.1.0", "2023-02-15")
task.add_milestone("v.1.1", "2023-08-01")
group = roadmap.add_group("Core Product Work Stream")

task = group.add_task("Base Functionality", "2023-01-01", "2023-10-31")
task.add_milestone("v.1.0", "2023-02-15")
task.add_milestone("v.1.1", "2023-08-01")
group = roadmap.add_group("Core Product Work Stream")

task = group.add_task("Base Functionality", "2023-01-01", "2023-10-31")
task.add_milestone("v.1.0", "2023-02-15")
task.add_milestone("v.1.1", "2023-08-01")

parellel_task = task.add_parallel_task("Enhancements", "2023-11-15", "2024-03-31")
parellel_task.add_milestone("v.2.0", "2024-03-30")

task = group.add_task("Showcase #1", "2023-03-01", "2023-05-07")
task.add_parallel_task("Showcase #2", "2023-06-01", "2023-08-07")
roadmap.set_footer("Generated by Roadmapper")
roadmap.draw()
roadmap.save("demo01.png")